#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/* ------------------------------------------------------------------
 * Central configuration. Tune thresholds and timing here.
 * ------------------------------------------------------------------ */

/* Peripheral handles generated by STM32CubeMX (change if yours differ) */
#define APP_UART_HANDLE         huart1   /* Nucleo-F446RE (ST-LINK VCP): huart2 */

/* Task periods (ms). FreeRTOS tick must be 1000 Hz (configTICK_RATE_HZ). */
#define TEMP_TASK_PERIOD_MS     100u
#define VIB_TASK_PERIOD_MS      2u       /* 500 Hz accelerometer sampling  */
#define ALARM_TASK_PERIOD_MS    100u
#define DISPLAY_TASK_PERIOD_MS  500u
#define UART_TASK_PERIOD_MS     1000u

/* Task priorities (added to tskIDLE_PRIORITY). Higher = more urgent. */
#define PRIO_VIBRATION          4u
#define PRIO_ALARM              3u
#define PRIO_TEMP               2u
#define PRIO_DISPLAY            1u
#define PRIO_UART               1u

/* Task stack sizes (in words, 1 word = 4 bytes on Cortex-M) */
#define STACK_VIBRATION         256u
#define STACK_ALARM             192u
#define STACK_TEMP              192u
#define STACK_DISPLAY           256u
#define STACK_UART              256u

/* --- Temperature (NTC thermistor in divider: 3V3 - R_FIXED - node - NTC - GND) --- */
#define ADC_MAX_COUNTS          4095u    /* 12-bit ADC                      */
#define ADC_OVERSAMPLE          16u      /* conversions averaged per read   */
#define NTC_R_FIXED_OHMS        10000.0f
#define NTC_R0_OHMS             10000.0f /* NTC resistance at T0            */
#define NTC_T0_C                25.0f
#define NTC_BETA                3950.0f
#define TEMP_MAVG_LEN           8u       /* moving-average window (samples) */

/* --- Vibration (MPU6050, +/-4 g range) --- */
#define VIB_WINDOW_SAMPLES      64u      /* RMS window: 64 x 2 ms = 128 ms  */
#define VIB_FAULT_LIMIT         10u      /* consecutive read errors => fault */

/* --- Alarm thresholds (demo values, tune for your setup) --- */
#define TEMP_WARN_C             50.0f
#define TEMP_CRIT_C             70.0f
#define TEMP_HYST_C             3.0f

#define VIB_WARN_G              0.30f    /* AC RMS, gravity removed         */
#define VIB_CRIT_G              1.00f
#define VIB_HYST_G              0.05f

#endif /* APP_CONFIG_H */
